### ISSUE TITLE
no actual performance gains on latest nodejs

### ISSUE THREAD

**Issue by olegmedoed** [mcollina/reusify#9]
I ran benchmark several times, so below you can see average result

![image](https://user-images.githubusercontent.com/4011317/45674722-598f6d00-bb36-11e8-97dd-502c40b26ce8.png)

**Comment by mcollina** [comment]
I know. However when I tried to remove it from some of the modules they slowed down in Node 8. Node 10 has a fix for the specific problem this module was needed for.

**Comment by olegmedoed** [comment]
Ok, in such case I close the issue. Btw, can you say where I can read about the fixes/improvements in Node regards this problem, thanks in advance.

**Comment by yunfan** [comment]
@mcollina is that means from node 10 we dont need this module? because from what i had test , its the reverse on performance

**Comment by mcollina** [comment]
I've tried removing this from a couple of places and I saw a perf degradation.
